//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTH.Infrastructure.Resource.Culture {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UTH.Infrastructure.Resource.Culture.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Category name 的本地化字符串。
        /// </summary>
        public static string basFenLeiMingCheng {
            get {
                return ResourceManager.GetString("basFenLeiMingCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission Action 的本地化字符串。
        /// </summary>
        public static string basQuanXianGongNeng {
            get {
                return ResourceManager.GetString("basQuanXianGongNeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission Manage 的本地化字符串。
        /// </summary>
        public static string basQuanXianGuanLi {
            get {
                return ResourceManager.GetString("basQuanXianGuanLi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission Nav 的本地化字符串。
        /// </summary>
        public static string basQuanXianLuJing {
            get {
                return ResourceManager.GetString("basQuanXianLuJing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application 的本地化字符串。
        /// </summary>
        public static string basYingYongChengXu {
            get {
                return ResourceManager.GetString("basYingYongChengXu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product name 的本地化字符串。
        /// </summary>
        public static string busChanPingMingCheng {
            get {
                return ResourceManager.GetString("busChanPingMingCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer already existed 的本地化字符串。
        /// </summary>
        public static string cstKeHuYiCunZai {
            get {
                return ResourceManager.GetString("cstKeHuYiCunZai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string DaKai {
            get {
                return ResourceManager.GetString("DaKai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string GuanBi {
            get {
                return ResourceManager.GetString("GuanBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 芝麻秘语-多语言及时翻译会议系统是一款支持当多语言的在线会议系统。支持全球主流的16种语言（汉语、英语、阿拉伯语、葡萄牙语、日语、泰语、西班牙语、印尼语）同声翻译：即时将当前获取到的语言转换成多种目标语言，并以文字的方式展现出来。 同时，通过扫描二维码，系统支持与手机的在线系统。 的本地化字符串。
        /// </summary>
        public static string metDescript {
            get {
                return ResourceManager.GetString("metDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会议错误 的本地化字符串。
        /// </summary>
        public static string metHuiYiCuoWu {
            get {
                return ResourceManager.GetString("metHuiYiCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会议界面 的本地化字符串。
        /// </summary>
        public static string metHuiYiJieMian {
            get {
                return ResourceManager.GetString("metHuiYiJieMian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会议记录服务异常 的本地化字符串。
        /// </summary>
        public static string metHuiYiJiLuFuWuYiChang {
            get {
                return ResourceManager.GetString("metHuiYiJiLuFuWuYiChang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会议设置 的本地化字符串。
        /// </summary>
        public static string metHuiYiSheZhi {
            get {
                return ResourceManager.GetString("metHuiYiSheZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会议室 的本地化字符串。
        /// </summary>
        public static string metHuiYiShi {
            get {
                return ResourceManager.GetString("metHuiYiShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入会议 的本地化字符串。
        /// </summary>
        public static string metJiaRuHuiYi {
            get {
                return ResourceManager.GetString("metJiaRuHuiYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始会议 的本地化字符串。
        /// </summary>
        public static string metKaiShiHuiYi {
            get {
                return ResourceManager.GetString("metKaiShiHuiYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 芝麻秘语-多语言即时翻译会议系统 的本地化字符串。
        /// </summary>
        public static string metName {
            get {
                return ResourceManager.GetString("metName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除会议记录 的本地化字符串。
        /// </summary>
        public static string metQingChuHuiYiJiLu {
            get {
                return ResourceManager.GetString("metQingChuHuiYiJiLu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入当前会议 的本地化字符串。
        /// </summary>
        public static string metQingShuRuDangQianHuiYi {
            get {
                return ResourceManager.GetString("metQingShuRuDangQianHuiYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到语音设备 的本地化字符串。
        /// </summary>
        public static string metWeiZhaoDaoYuYinSeBei {
            get {
                return ResourceManager.GetString("metWeiZhaoDaoYuYinSeBei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程数据服务异常 的本地化字符串。
        /// </summary>
        public static string metYuanChengShuJuYiChang {
            get {
                return ResourceManager.GetString("metYuanChengShuJuYiChang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语音识别服务异常 的本地化字符串。
        /// </summary>
        public static string metYuYingShiBieFuWuYiChang {
            get {
                return ResourceManager.GetString("metYuYingShiBieFuWuYiChang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在导出会议记录 的本地化字符串。
        /// </summary>
        public static string metZhengZaiDaoChuHuiYiJiLu {
            get {
                return ResourceManager.GetString("metZhengZaiDaoChuHuiYiJiLu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在会议 的本地化字符串。
        /// </summary>
        public static string metZhengZaiHuiYi {
            get {
                return ResourceManager.GetString("metZhengZaiHuiYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理中心 的本地化字符串。
        /// </summary>
        public static string mgName {
            get {
                return ResourceManager.GetString("mgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信号码或内容错误 的本地化字符串。
        /// </summary>
        public static string plugDuanXinHaoMaHuoNeiRongCuoWu {
            get {
                return ResourceManager.GetString("plugDuanXinHaoMaHuoNeiRongCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version is new 的本地化字符串。
        /// </summary>
        public static string synDangQianWeiZuiXinBanBeng {
            get {
                return ResourceManager.GetString("synDangQianWeiZuiXinBanBeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string sysBangZhu {
            get {
                return ResourceManager.GetString("sysBangZhu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help Center 的本地化字符串。
        /// </summary>
        public static string sysBangZhuZhongXin {
            get {
                return ResourceManager.GetString("sysBangZhuZhongXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string sysBaoCun {
            get {
                return ResourceManager.GetString("sysBaoCun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string sysBaoCunChengGong {
            get {
                return ResourceManager.GetString("sysBaoCunChengGong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string sysBianJi {
            get {
                return ResourceManager.GetString("sysBianJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码 的本地化字符串。
        /// </summary>
        public static string sysBianMa {
            get {
                return ResourceManager.GetString("sysBianMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码已存在 的本地化字符串。
        /// </summary>
        public static string sysBianMaYiCunZai {
            get {
                return ResourceManager.GetString("sysBianMaYiCunZai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate 的本地化字符串。
        /// </summary>
        public static string sysCaoZuo {
            get {
                return ResourceManager.GetString("sysCaoZuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        public static string sysCaoZuoChengGong {
            get {
                return ResourceManager.GetString("sysCaoZuoChengGong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName} must be {MinLength} - {MaxLength} characters 的本地化字符串。
        /// </summary>
        public static string sysChangDuQuJianFormat {
            get {
                return ResourceManager.GetString("sysChangDuQuJianFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找 的本地化字符串。
        /// </summary>
        public static string sysChaZhao {
            get {
                return ResourceManager.GetString("sysChaZhao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string sysChengGong {
            get {
                return ResourceManager.GetString("sysChengGong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已经运行，请勿重复操作！ 的本地化字符串。
        /// </summary>
        public static string sysChengXuYiJingYunXingQingWuChongFuCaoZuo {
            get {
                return ResourceManager.GetString("sysChengXuYiJingYunXingQingWuChongFuCaoZuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rest 的本地化字符串。
        /// </summary>
        public static string sysChongZhi {
            get {
                return ResourceManager.GetString("sysChongZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始失败 的本地化字符串。
        /// </summary>
        public static string sysChuShiShiBai {
            get {
                return ResourceManager.GetString("sysChuShiShiBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTH国际 的本地化字符串。
        /// </summary>
        public static string sysCompany {
            get {
                return ResourceManager.GetString("sysCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Engine Config File Error {0} 的本地化字符串。
        /// </summary>
        public static string sysConfigEngineError {
            get {
                return ResourceManager.GetString("sysConfigEngineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config File Error ({0}) 的本地化字符串。
        /// </summary>
        public static string sysConfigFileError {
            get {
                return ResourceManager.GetString("sysConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string sysCuoWu {
            get {
                return ResourceManager.GetString("sysCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version 的本地化字符串。
        /// </summary>
        public static string sysDangQianBanBeng {
            get {
                return ResourceManager.GetString("sysDangQianBanBeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string sysDaoChu {
            get {
                return ResourceManager.GetString("sysDaoChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒计时 的本地化字符串。
        /// </summary>
        public static string sysDaoJiShi {
            get {
                return ResourceManager.GetString("sysDaoJiShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sms code error 的本地化字符串。
        /// </summary>
        public static string sysDuanXinYanZhengMaCuoWu {
            get {
                return ResourceManager.GetString("sysDuanXinYanZhengMaCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回上级 的本地化字符串。
        /// </summary>
        public static string sysFanHuiShangJi {
            get {
                return ResourceManager.GetString("sysFanHuiShangJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送成功 的本地化字符串。
        /// </summary>
        public static string sysFaSongChengGong {
            get {
                return ResourceManager.GetString("sysFaSongChengGong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送失败 的本地化字符串。
        /// </summary>
        public static string sysFaSongShiBai {
            get {
                return ResourceManager.GetString("sysFaSongShiBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本 的本地化字符串。
        /// </summary>
        public static string sysFaXianXinBanBeng {
            get {
                return ResourceManager.GetString("sysFaXianXinBanBeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务异常 的本地化字符串。
        /// </summary>
        public static string sysFuWuYiChang {
            get {
                return ResourceManager.GetString("sysFuWuYiChang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string sysGengXin {
            get {
                return ResourceManager.GetString("sysGengXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update ..... 的本地化字符串。
        /// </summary>
        public static string sysGengXinChengXu {
            get {
                return ResourceManager.GetString("sysGengXinChengXu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string sysGuanYu {
            get {
                return ResourceManager.GetString("sysGuanYu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于我们 的本地化字符串。
        /// </summary>
        public static string sysGuanYuWoMen {
            get {
                return ResourceManager.GetString("sysGuanYuWoMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取验证码 的本地化字符串。
        /// </summary>
        public static string sysHuoQuYanZhengMa {
            get {
                return ResourceManager.GetString("sysHuoQuYanZhengMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查 的本地化字符串。
        /// </summary>
        public static string sysJianCha {
            get {
                return ResourceManager.GetString("sysJianCha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base Info 的本地化字符串。
        /// </summary>
        public static string sysJiChuXinXi {
            get {
                return ResourceManager.GetString("sysJiChuXinXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果为空 的本地化字符串。
        /// </summary>
        public static string sysJieGuoWeiKong {
            get {
                return ResourceManager.GetString("sysJieGuoWeiKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        public static string sysKey {
            get {
                return ResourceManager.GetString("sysKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string sysLeiXing {
            get {
                return ResourceManager.GetString("sysLeiXing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string sysLiJiGengXin {
            get {
                return ResourceManager.GetString("sysLiJiGengXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string sysLiJiTiJiao {
            get {
                return ResourceManager.GetString("sysLiJiTiJiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logger Error ({0}:{1}) 的本地化字符串。
        /// </summary>
        public static string sysLoggerAdapterError {
            get {
                return ResourceManager.GetString("sysLoggerAdapterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string sysMingCheng {
            get {
                return ResourceManager.GetString("sysMingCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称已存在 的本地化字符串。
        /// </summary>
        public static string sysMingChengYiCunZai {
            get {
                return ResourceManager.GetString("sysMingChengYiCunZai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密钥 的本地化字符串。
        /// </summary>
        public static string sysMiYao {
            get {
                return ResourceManager.GetString("sysMiYao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string sysName {
            get {
                return ResourceManager.GetString("sysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量添加 的本地化字符串。
        /// </summary>
        public static string sysPiLiangTianJia {
            get {
                return ResourceManager.GetString("sysPiLiangTianJia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch 的本地化字符串。
        /// </summary>
        public static string sysQieHuan {
            get {
                return ResourceManager.GetString("sysQieHuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your {PropertyName} 的本地化字符串。
        /// </summary>
        public static string sysQingShuRuFormat {
            get {
                return ResourceManager.GetString("sysQingShuRuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter search key 的本地化字符串。
        /// </summary>
        public static string sysQingShuRuGuanJianZi {
            get {
                return ResourceManager.GetString("sysQingShuRuGuanJianZi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter name 的本地化字符串。
        /// </summary>
        public static string sysQingShuRuMingCheng {
            get {
                return ResourceManager.GetString("sysQingShuRuMingCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid {PropertyName} 的本地化字符串。
        /// </summary>
        public static string sysQingShuRuYouXiaoFormat {
            get {
                return ResourceManager.GetString("sysQingShuRuYouXiaoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select type 的本地化字符串。
        /// </summary>
        public static string sysQingXuanZeLeiXing {
            get {
                return ResourceManager.GetString("sysQingXuanZeLeiXing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择删除数据 的本地化字符串。
        /// </summary>
        public static string sysQingXuanZeShanChuShuJu {
            get {
                return ResourceManager.GetString("sysQingXuanZeShanChuShuJu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择修改数据 的本地化字符串。
        /// </summary>
        public static string sysQingXuanZeXiuGaiShuJu {
            get {
                return ResourceManager.GetString("sysQingXuanZeXiuGaiShuJu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string sysQueDing {
            get {
                return ResourceManager.GetString("sysQueDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string sysQueRen {
            get {
                return ResourceManager.GetString("sysQueRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string sysQuXiao {
            get {
                return ResourceManager.GetString("sysQuXiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string sysShanChu {
            get {
                return ResourceManager.GetString("sysShanChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string sysSheZhi {
            get {
                return ResourceManager.GetString("sysSheZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除数据 的本地化字符串。
        /// </summary>
        public static string sysShiFouShanChuShuJu {
            get {
                return ResourceManager.GetString("sysShiFouShanChuShuJu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试用版 的本地化字符串。
        /// </summary>
        public static string sysShiYongBan {
            get {
                return ResourceManager.GetString("sysShiYongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorized usage exceeded 的本地化字符串。
        /// </summary>
        public static string sysShouQuanShiYongCiShuYiChaoChu {
            get {
                return ResourceManager.GetString("sysShouQuanShiYongCiShuYiChaoChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License file error. 的本地化字符串。
        /// </summary>
        public static string sysShouQuanWenJianCuoWu {
            get {
                return ResourceManager.GetString("sysShouQuanWenJianCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License info error. 的本地化字符串。
        /// </summary>
        public static string sysShouQuanXinXiCuoWu {
            get {
                return ResourceManager.GetString("sysShouQuanXinXiCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License is expire 的本地化字符串。
        /// </summary>
        public static string sysShouQuanYiGuoQi {
            get {
                return ResourceManager.GetString("sysShouQuanYiGuoQi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index 的本地化字符串。
        /// </summary>
        public static string sysShouYe {
            get {
                return ResourceManager.GetString("sysShouYe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string sysSouSuo {
            get {
                return ResourceManager.GetString("sysSouSuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string sysTianJia {
            get {
                return ResourceManager.GetString("sysTianJia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string sysTiJiao {
            get {
                return ResourceManager.GetString("sysTiJiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip 的本地化字符串。
        /// </summary>
        public static string sysTiShi {
            get {
                return ResourceManager.GetString("sysTiShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多语会议系统 的本地化字符串。
        /// </summary>
        public static string sysTitle {
            get {
                return ResourceManager.GetString("sysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知发送错误 的本地化字符串。
        /// </summary>
        public static string sysTongZhiFaSongCuoWu {
            get {
                return ResourceManager.GetString("sysTongZhiFaSongCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知类型错误 的本地化字符串。
        /// </summary>
        public static string sysTongZhiLeiXinCuoWu {
            get {
                return ResourceManager.GetString("sysTongZhiLeiXinCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我已阅读 的本地化字符串。
        /// </summary>
        public static string sysWoYiYueDu {
            get {
                return ResourceManager.GetString("sysWoYiYueDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string sysXiaYiBu {
            get {
                return ResourceManager.GetString("sysXiaYiBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string sysXinXi {
            get {
                return ResourceManager.GetString("sysXinXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        public static string sysXinXiBiaoTi {
            get {
                return ResourceManager.GetString("sysXinXiBiaoTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        public static string sysXiTont {
            get {
                return ResourceManager.GetString("sysXiTont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string sysXiuGai {
            get {
                return ResourceManager.GetString("sysXiuGai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string sysXuanZe {
            get {
                return ResourceManager.GetString("sysXuanZe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证失败 的本地化字符串。
        /// </summary>
        public static string sysYanZhengShiBai {
            get {
                return ResourceManager.GetString("sysYanZhengShiBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 selected &lt;em&gt;{0}&lt;/em&gt; items 的本地化字符串。
        /// </summary>
        public static string sysYiXuanZeXiang {
            get {
                return ResourceManager.GetString("sysYiXuanZeXiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string sysZengJia {
            get {
                return ResourceManager.GetString("sysZengJia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正式版 的本地化字符串。
        /// </summary>
        public static string sysZhengShiBan {
            get {
                return ResourceManager.GetString("sysZhengShiBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动 的本地化字符串。
        /// </summary>
        public static string sysZhengZaiQiDong {
            get {
                return ResourceManager.GetString("sysZhengZaiQiDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string sysZhuangTai {
            get {
                return ResourceManager.GetString("sysZhuangTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Version 的本地化字符串。
        /// </summary>
        public static string sysZuiXinBanBeng {
            get {
                return ResourceManager.GetString("sysZuiXinBanBeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string userDengLu {
            get {
                return ResourceManager.GetString("userDengLu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        public static string userDengLuShiBai {
            get {
                return ResourceManager.GetString("userDengLuShiBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回登录 的本地化字符串。
        /// </summary>
        public static string userFanHuiDengLu {
            get {
                return ResourceManager.GetString("userFanHuiDengLu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人信息 的本地化字符串。
        /// </summary>
        public static string userGeRenXinXi {
            get {
                return ResourceManager.GetString("userGeRenXinXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        public static string userJiZhuMiMa {
            get {
                return ResourceManager.GetString("userJiZhuMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有账号 的本地化字符串。
        /// </summary>
        public static string userMeiYouZhangHao {
            get {
                return ResourceManager.GetString("userMeiYouZhangHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string userMiMa {
            get {
                return ResourceManager.GetString("userMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Error 的本地化字符串。
        /// </summary>
        public static string userMiMaCuoWu {
            get {
                return ResourceManager.GetString("userMiMaCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认新密码 的本地化字符串。
        /// </summary>
        public static string userQingQueRenXinMiMa {
            get {
                return ResourceManager.GetString("userQingQueRenXinMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        public static string userQingShuRuMiMa {
            get {
                return ResourceManager.GetString("userQingShuRuMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入手机号 的本地化字符串。
        /// </summary>
        public static string userQingShuRuShouJiHao {
            get {
                return ResourceManager.GetString("userQingShuRuShouJiHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入新密码 的本地化字符串。
        /// </summary>
        public static string userQingShuRuXinMiMa {
            get {
                return ResourceManager.GetString("userQingShuRuXinMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入验证码 的本地化字符串。
        /// </summary>
        public static string userQingShuRuYanZhengMa {
            get {
                return ResourceManager.GetString("userQingShuRuYanZhengMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入有效的确认密码 的本地化字符串。
        /// </summary>
        public static string userQingShuRuYouXiaoDeQueRenMiMa {
            get {
                return ResourceManager.GetString("userQingShuRuYouXiaoDeQueRenMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入有效的新密码 的本地化字符串。
        /// </summary>
        public static string userQingShuRuYouXiaoDeXinMiMa {
            get {
                return ResourceManager.GetString("userQingShuRuYouXiaoDeXinMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入有效的原密码 的本地化字符串。
        /// </summary>
        public static string userQingShuRuYouXiaoDeYuanMiMa {
            get {
                return ResourceManager.GetString("userQingShuRuYouXiaoDeYuanMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入账号 的本地化字符串。
        /// </summary>
        public static string userQingShuRuZhangHao {
            get {
                return ResourceManager.GetString("userQingShuRuZhangHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter account,mobile,email 的本地化字符串。
        /// </summary>
        public static string userQingShuRuZhangHaoShouJiHaoMaYouXiangDiZhi {
            get {
                return ResourceManager.GetString("userQingShuRuZhangHaoShouJiHaoMaYouXiangDiZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的手机号 的本地化字符串。
        /// </summary>
        public static string userQingShuRuZhengQueDeShouJiHao {
            get {
                return ResourceManager.GetString("userQingShuRuZhengQueDeShouJiHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的验证码 的本地化字符串。
        /// </summary>
        public static string userQingShuRuZhengQueDeYanZhengMa {
            get {
                return ResourceManager.GetString("userQingShuRuZhengQueDeYanZhengMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter account / password 的本地化字符串。
        /// </summary>
        public static string userQingShuZhaoHaoMiMa {
            get {
                return ResourceManager.GetString("userQingShuZhaoHaoMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请阅读并同意注册协议 的本地化字符串。
        /// </summary>
        public static string userQingYueDuBingTongYiZhuCeXieYi {
            get {
                return ResourceManager.GetString("userQingYueDuBingTongYiZhuCeXieYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string userQueRenMiMa {
            get {
                return ResourceManager.GetString("userQueRenMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile 的本地化字符串。
        /// </summary>
        public static string userShouJiHaoMa {
            get {
                return ResourceManager.GetString("userShouJiHaoMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string userTuiChu {
            get {
                return ResourceManager.GetString("userTuiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出登录 的本地化字符串。
        /// </summary>
        public static string userTuiChuDengLu {
            get {
                return ResourceManager.GetString("userTuiChuDengLu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我已同意 的本地化字符串。
        /// </summary>
        public static string userWoYiTongYi {
            get {
                return ResourceManager.GetString("userWoYiTongYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我已同意《用户注册协议》 的本地化字符串。
        /// </summary>
        public static string userWoYiTongYiYongHuZhuCeXieYi {
            get {
                return ResourceManager.GetString("userWoYiTongYiYongHuZhuCeXieYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string userXingMing {
            get {
                return ResourceManager.GetString("userXingMing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string userXinMiMa {
            get {
                return ResourceManager.GetString("userXinMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码与确认密码不同 的本地化字符串。
        /// </summary>
        public static string userXinMiMaYuQueRenMiMaBuTong {
            get {
                return ResourceManager.GetString("userXinMiMaYuQueRenMiMaBuTong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string userXiuGaiMiMa {
            get {
                return ResourceManager.GetString("userXiuGaiMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Code 的本地化字符串。
        /// </summary>
        public static string userYanZhengMa {
            get {
                return ResourceManager.GetString("userYanZhengMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code error 的本地化字符串。
        /// </summary>
        public static string userYanZhengMaCuoWu {
            get {
                return ResourceManager.GetString("userYanZhengMaCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已有账号 的本地化字符串。
        /// </summary>
        public static string userYiYouZhangHao {
            get {
                return ResourceManager.GetString("userYiYouZhangHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string userYongHu {
            get {
                return ResourceManager.GetString("userYongHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string userYongHuGuanLi {
            get {
                return ResourceManager.GetString("userYongHuGuanLi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户添加 的本地化字符串。
        /// </summary>
        public static string userYongHuTianJia {
            get {
                return ResourceManager.GetString("userYongHuTianJia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号 的本地化字符串。
        /// </summary>
        public static string userYongHuZhangHao {
            get {
                return ResourceManager.GetString("userYongHuZhangHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户注册 的本地化字符串。
        /// </summary>
        public static string userYongHuZhuCe {
            get {
                return ResourceManager.GetString("userYongHuZhuCe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户注册协议 的本地化字符串。
        /// </summary>
        public static string userYongHuZhuCeXieYi {
            get {
                return ResourceManager.GetString("userYongHuZhuCeXieYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新用户注册 的本地化字符串。
        /// </summary>
        public static string userYongYuZhuCeXin {
            get {
                return ResourceManager.GetString("userYongYuZhuCeXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email code error 的本地化字符串。
        /// </summary>
        public static string userYouJianYanZhengMaCuoWu {
            get {
                return ResourceManager.GetString("userYouJianYanZhengMaCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string userYouXiangDiZhi {
            get {
                return ResourceManager.GetString("userYouXiangDiZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原密码 的本地化字符串。
        /// </summary>
        public static string userYuanMiMa {
            get {
                return ResourceManager.GetString("userYuanMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        public static string userZhangHao {
            get {
                return ResourceManager.GetString("userZhangHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Error 的本地化字符串。
        /// </summary>
        public static string userZhangHaoCuoWu {
            get {
                return ResourceManager.GetString("userZhangHaoCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号管理 的本地化字符串。
        /// </summary>
        public static string userZhangHaoGuanLi {
            get {
                return ResourceManager.GetString("userZhangHaoGuanLi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account already existed 的本地化字符串。
        /// </summary>
        public static string userZhangHuYiCunZai {
            get {
                return ResourceManager.GetString("userZhangHuYiCunZai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找回密码 的本地化字符串。
        /// </summary>
        public static string userZhaoHuiMiMa {
            get {
                return ResourceManager.GetString("userZhaoHuiMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您正在找回 UTH 账号，验证码为 {0}，验证码10分钟内有效，祝您使用愉快！ 的本地化字符串。
        /// </summary>
        public static string userZhaoHuiMiMaYanZhengMaXiaoXi {
            get {
                return ResourceManager.GetString("userZhaoHuiMiMaYanZhengMaXiaoXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regist 的本地化字符串。
        /// </summary>
        public static string userZhuCe {
            get {
                return ResourceManager.GetString("userZhuCe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register Success 的本地化字符串。
        /// </summary>
        public static string userZhuCeChengGongXiaoXi {
            get {
                return ResourceManager.GetString("userZhuCeChengGongXiaoXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register fail 的本地化字符串。
        /// </summary>
        public static string userZhuCeShiBai {
            get {
                return ResourceManager.GetString("userZhuCeShiBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您正在注册 UTH 账号，验证码为 {0}，验证码10分钟内有效，祝您使用愉快！ 的本地化字符串。
        /// </summary>
        public static string userZhuCeYanZhengMaXiaoXi {
            get {
                return ResourceManager.GetString("userZhuCeYanZhengMaXiaoXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup 的本地化字符串。
        /// </summary>
        public static string winQiDongQi {
            get {
                return ResourceManager.GetString("winQiDongQi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Update ...... 的本地化字符串。
        /// </summary>
        public static string winUpdate {
            get {
                return ResourceManager.GetString("winUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string winZhuJieMian {
            get {
                return ResourceManager.GetString("winZhuJieMian", resourceCulture);
            }
        }
    }
}
